// import { Geist, Geist_Mono } from "next/font/google";
import Footer from "@/components/Footer";
import "./globals.css";
import HeroPage from "./Hero/Page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
      <HeroPage/>
      <div className="main">
        {children}
      </div>
      <Footer/>
      </body>
    </html>
  );
}
