import "./globals.css";
import { Trochut, Sunflower } from 'next/font/google'

const trochut = Trochut({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-trochut',
})

const sunflower = Sunflower({
  subsets: ['latin'],
  weight: ['300', '500', '700'],
  variable: '--font-sunflower',
})
import Footer from "@/components/Footer";
import HeroPage from "./Hero/Page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${trochut.variable} ${sunflower.variable}`}>
      <body
      >
      <HeroPage/>
      <div className="main">
        {children}
      </div>
      <Footer/>
      </body>
    </html>
  );
}
